#!/bin/bash -ex

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive

minimal_apt_get_install() {
  if [[ ! -e /var/lib/apt/lists/lock ]]; then
    apt-get update
  fi
  apt-get install -y --no-install-recommends "$@"
}

[ -z $APP_USER ] && exit 1
[ -z $APP_SRC_DIR ] && exit 1
[ -z $BUNDLE_PATH ] && exit 1

# add ppa for latest ruby
echo deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu trusty main > /etc/apt/sources.list.d/brightbox.list

# add ppa for stable nginx
echo deb http://ppa.launchpad.net/nginx/stable/ubuntu trusty main > /etc/apt/sources.list.d/nginx.list

# add keys for PPAs
#
# Brightbox
# Nginx
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys \
  C3173AA6 \
  8B3981E7A6852F782CC4951600A6F0A3C300EE8C

# add ppa for node (also runs apt-get update)
curl --fail -ssL -o /tmp/setup-nodejs https://deb.nodesource.com/setup_0.12
bash /tmp/setup-nodejs
rm -f /tmp/setup-nodejs

# install deps
minimal_apt_get_install \
  build-essential \
  git \
  libcurl4-openssl-dev \
  libpq-dev \
  libxml2-dev \
  libxslt1-dev \
  locales \
  nginx \
  nodejs \
  ruby2.2 \
  ruby2.2-dev \
  zlib1g-dev \
  #

# ensure we have en_US.UTF-8
locale-gen en_US.UTF-8

# create $APP_USER user
addgroup --gid 9999 $APP_USER
adduser --uid 9999 --gid 9999 --disabled-password --gecos "Application" $APP_USER
usermod -L $APP_USER
mkdir -p /home/$APP_USER/.ssh
chmod 700 /home/$APP_USER/.ssh
chown $APP_USER:$APP_USER /home/$APP_USER/.ssh

# application code will live here
mkdir -p $APP_SRC_DIR
chown $APP_USER:$APP_USER $APP_SRC_DIR
cd /home/$APP_USER && ln -s $APP_SRC_DIR

# application gems will live here
mkdir $BUNDLE_PATH
chown $APP_USER:$APP_USER $BUNDLE_PATH

# skip installing gem documentation
echo 'gem: --no-rdoc --no-ri' >> "/etc/gemrc"

# bundler should be the only global gem
gem install bundler

# setup unattended upgrades to run automatically
cp /build/config/apt_apt_conf_d_20auto-upgrades /etc/apt/apt.conf.d/20auto-upgrades

# setup nginx
rm /etc/nginx/sites-enabled/default
cp /build/config/nginx.conf /etc/nginx/nginx.conf
mkdir -p /etc/nginx/main.d
cp /build/config/nginx_main_d_default.conf /etc/nginx/main.d/default.conf
mkdir /etc/service/nginx
cp /build/runit/nginx /etc/service/nginx/run
mkdir /etc/service/nginx-log-forwarder
cp /build/runit/nginx-log-forwarder /etc/service/nginx-log-forwarder/run
